repos:
-   repo: local
    hooks:
    -   id: isort
        name: isort
        description: ordering imports
        entry: isort --settings-path setup.cfg --src auth/src
        verbose: true
        language: python
        types: [python]
