version: '3'
services:
  admin_postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - pg_data_admin:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_ADMIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ADMIN}
      POSTGRES_USER: ${POSTGRES_USER_ADMIN}

  elastic:
    image: elasticsearch:7.17.5
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_value:/usr/share/elasticsearch/data
    expose:
      - "9200"
    depends_on:
      - admin_postgres

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    expose:
      - "6379"

  admin_panel:
    build: admin_panel
    restart: unless-stopped
    volumes:
      - service_static_value:/opt/app/static/
      - service_media_value:/opt/app/media/
    expose:
      - "8000"
    env_file:
      - ./.env

  fastapi:
    build: fastapi
    depends_on:
      - elastic
      - redis
    expose:
      - "8000"
    env_file:
      - ./.env
    entrypoint: ["./wait-for-it.sh", "-s", "-t", "0", "elastic:9200", "--"]
    command: ["gunicorn", "-b", "0.0.0.0:8000", "--workers", "4", "-k", "uvicorn.workers.UvicornWorker", "src.main:app"]

  nginx:
    image: nginx:1.23
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - service_static_value:/var/html/static/
      - service_media_value:/var/html/media/
      - /tmp/logs/nginx/:/var/log/nginx/
    depends_on:
      - fastapi
      - admin_panel
      - auth_flask
      - activity_api
    ports:
      - "8000:80"

  etl:
    build: etl_services
    volumes:
      - ./etl_services:/opt/app:ro
    env_file:
      - ./.env
    depends_on:
      - elastic
    entrypoint: ["./wait-for-it.sh", "-s", "-t", "0", "elastic:9200", "--"]
    command: ["python3", "/opt/app/postgres_to_es/load_indexes.py"]

  auth_postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - pg_data_auth:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
      POSTGRES_USER: ${POSTGRES_USER_AUTH}

  auth_flask:
    build: auth
    volumes:
      - /tmp/logs/auth_flask/:/var/log/auth_flask/
    depends_on:
      - auth_postgres
      - redis
    expose:
      - "5000"
    env_file:
      - .env
    entrypoint: >
      sh -c "python /opt/app/src/manage.py db upgrade head
      && gunicorn -b 0.0.0.0:5000 --workers 4 src.pywsgi:app"

  jaeger:
    image: jaegertracing/all-in-one:1.39.0
    depends_on:
      - auth_flask
    expose:
      - "16686"
      - "6831"
    ports:
      - "16686:16686"
      - "6831:6831/udp"

  activity_api:
    build: activity_api
    volumes:
      - /tmp/logs/activity_api/:/var/log/activity_api/
    expose:
      - "8000"
    env_file:
      - ./.env
    entrypoint: ["./wait-for-it.sh", "-s", "-t", "600", "${EVENT_STORE_HOST}:${EVENT_STORE_PORT}", "--"]
    command: ["gunicorn", "-b", "0.0.0.0:8000", "--workers", "4", "-k", "uvicorn.workers.UvicornWorker", "src.main:app"]

  elk_logstash:
    image: logstash:7.10.1
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: ${ELK_ES_HOST}
    ports:
      - "5044:5044/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  elkelasticsearch:
    image: elasticsearch:7.17.5
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    volumes:
      - elk_elasticsearch_value:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9201:9200"

  elk_kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    environment:
      ELASTICSEARCH_HOSTS: ${ELK_ES_HOST}
    ports:
      - "5601:5601"
    depends_on:
      - elkelasticsearch

  elk_filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.2
    environment:
      ELK_LOGSTASH_HOST: ${ELK_LOGSTASH_HOST}
    command: filebeat -e -strict.perms=false
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - /tmp/logs/auth_flask/:/var/log/auth_flask:ro
      - /tmp/logs/activity_api/:/var/log/activity_api:ro
      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - nginx
      - elk_logstash
      - elkelasticsearch
      - elk_kibana
    links:
      - elk_logstash


volumes:
  service_static_value:
  service_media_value:
  elasticsearch_value:
  elk_elasticsearch_value:
  pg_data_admin:
  pg_data_auth: