filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*
  json:
    keys_under_root: true
    add_error_key: true
  tags: ["nginx"]

- type: log
  enabled: true
  paths:
    - /var/log/auth-flask/*
  json:
    keys_under_root: true
    add_error_key: true
  tags: ["auth-flask"]

output.logstash:
  enabled: true
  hosts: ["${ELK_LOGSTASH_HOST}"]