name: Online Cinema application workflow

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: | 
        python3 -m pip install --upgrade pip                
        pip install flake8 flake8-isort

    - name: Test with flake8
      run: |
        python3 -m flake8 .
    
  build_and_push_to_docker_hub:  
    name: Push Docker image to Docker Hub
    needs: tests
    runs-on: ubuntu-latest    
    #env:
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1   
        with:     
          POSTGRES_DB_AUTH: ${{ secrets.POSTGRES_DB_AUTH }}
          POSTGRES_PASSWORD_AUTH: ${{ github.POSTGRES_PASSWORD_AUTH }}
          POSTGRES_USER_AUTH: ${{ github.POSTGRES_USER_AUTH }}
          compose-file: "./auth/tests/functional/docker-compose.yml"
          
