name: Online Cinema application workflow

on: [pull_request]

jobs:
  variables:
    POSTGRES_DB_AUTH: 'movies_database'
    POSTGRES_PASSWORD_AUTH: '123qwe'
    POSTGRES_USER_AUTH: 'app'


  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: | 
        python3 -m pip install --upgrade pip                
        pip install flake8 flake8-isort

    - name: Test with flake8
      run: |
        python3 -m flake8 .
    
  build_and_push_to_docker_hub:  
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./auth/tests/functional/docker-compose.yml"
          env:
            POSTGRES_DB_AUTH: $POSTGRES_DB_AUTH
            POSTGRES_PASSWORD_AUTH: $POSTGRES_PASSWORD_AUTH
            POSTGRES_USER_AUTH: $POSTGRES_USER_AUTH 
